# Generated by Django 2.2.6 on 2019-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('primary_device_os', models.CharField(max_length=64)),
                ('device_type', models.CharField(max_length=64)),
            ],
        ),
    ]
