# Generated by Django 2.2.6 on 2019-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbot', '0003_auto_20191112_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='viber_id',
            field=models.CharField(max_length=256),
        ),
    ]
